export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/teachers";
export * from "@/pages/dashboard/createteachers";
export * from "@/pages/dashboard/courses"
export * from "@/pages/dashboard/createcourses";
export * from "@/pages/dashboard/rooms";
export * from "@/pages/dashboard/createrooms";
export * from "@/pages/dashboard/semesters";
export * from "@/pages/dashboard/createsemesters";
